services:
  git-checkout:
    image: bitnami/git:latest
    working_dir: /temp
    command: >
      bash -c "
        git clone https://github.com/benjiao/homelab.git &&
        cp -R ./homelab/docker/grafana/prometheus.yml /etc/prometheus_config/prometheus.yml
      "
    volumes:
      - prometheus_config:/etc/prometheus_config

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      # - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
      - prometheus_config:/etc/prometheus_config
    command:
      - '--config.file=/etc/prometheus_config/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.size=30GB'
      - '--web.console.libraries=/etc/prometheus_config/console_libraries'
      - '--web.console.templates=/etc/prometheus_config/consoles'
      - '--web.enable-lifecycle'
      - '--web.external-url=${PROMETHEUS_EXTERNAL_URL:-http://localhost:9090}'
    ports:
      - '${PROMETHEUS_PORT:-9090}:9090'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - '${GRAFANA_PORT:-3000}:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.benjiao.net/
    networks:
      - monitoring

volumes:
  grafana_data:
  prometheus_data:
  prometheus_config:

networks:
  monitoring:
    driver: bridge