global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['192.168.0.85:9100']
        labels:
          hostname: 'pve'
      - targets: ['192.168.0.31:9100']
        labels:
          hostname: 'pi01'
      - targets: ['192.168.0.33:9100']
        labels:
          hostname: 'pi02'
      - targets: ['192.168.0.100:9100']
        labels:
          hostname: 'benjiao-ws1'