services:
  app:
    image: ghcr.io/manyfold3d/manyfold:latest
    ports:
      - ${MANYFOLD_PORT:-3214}:3214
    volumes:
      - manyfold_models:/models
    environment:
      DATABASE_ADAPTER: postgresql
      DATABASE_HOST: postgres-server
      DATABASE_PORT: 5432 # only needed for non-standard ports
      DATABASE_NAME: manyfold # or the path to the database file if using sqlite3
      DATABASE_USER: manyfold
      DATABASE_PASSWORD: ${MANYFOLD_DB_PASSWORD}
      SECRET_KEY_BASE: ${MANYFOLD_SECRET_KEY_BASE}
      REDIS_URL: redis://redis-server:6379/1
      MANYFOLD_HOST: ${MANYFOLD_HOST:-https://manyfold.benjiao.net}
      RAILS_FORCE_SSL: ${MANYFOLD_FORCE_SSL:-true}
      SUDO_RUN_UNSAFELY: ${SUDO_RUN_UNSAFELY:-enabled}
    restart: unless-stopped
    depends_on:
      - postgres-server
      - redis-server
    networks:
      - manyfold
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID

  postgres-server:
    image: postgres:15
    volumes:
      - manyfold_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: manyfold
      POSTGRES_PASSWORD: ${MANYFOLD_DB_PASSWORD}
    restart: unless-stopped
    networks:
      - manyfold

  redis-server:
    image: redis:7
    restart: unless-stopped
    networks:
      - manyfold

volumes:
  manyfold_db_data:
  manyfold_models:

networks:
  manyfold: